# Generated by Django 3.0.9 on 2020-11-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201110_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='describtion',
            new_name='description',
        ),
    ]
